version: 1
formatters:
  simple:
    format: '%(asctime)s | %(name)s | %(levelname)s | %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
  file:
    class: logging.FileHandler
    filename: logs/nlp-spacy-tool.log
    mode: w
    level: DEBUG
    formatter: simple
loggers:
  root:
    level: ERROR
    handlers: [console]
  tool:
    level: DEBUG
    handlers: [console, file]
  spacy:
    level: DEBUG
    handlers: [console, file]
  openapi_server:
    level: DEBUG
    handlers: [console, file]